### DISCUSSION TITLE
How should `<body>` framing work with UIShell?

### DISCUSSION THREAD

**Discussion by theetrain** [carbon-design-system/carbon-components-svelte#1432] [Q&A] [answered]
Hello, and thanks for maintaining this fantastic library.

I noticed in the [UIShell documentation](https://carbon-components-svelte.onrender.com/components/UIShell#header-with-side-navigation-rail) the placement of `<SideNav>` changes depending on whether its `rail` formation is used.

- If `rail` is used, then `<SideNav>` is a child of `<Header>`
- In all other cases, `<SideNav>` is a next sibling of `<Header>`

The UIShell examples also appear to have a `framed` class applied to `<body>` that seems necessary for spacing to cooperate with items placed in `<Content>`, but this `framed` class isn't documented nor apparently available. I want to take advantage of the spacing fix applied in the recent release: [v0.67.7](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.67.7).

With that said, here are my questions:

1. Is there a way to apply `rail` such as `<SideNav {rail}>` without having to change its position in the DOM? Currently I'm making use of `{#if}` to render `<SideNav>` either inside our outside `<Header>` depending on the situation I want to use `rail` in.
   - Workaround: After exploring this a bit, it seems `<SideNav>` can be placed as a direct sibling of `<Header>` and have good spacing next to `<Content>` whether or not `rail` is used. 🤔 Maybe the documented examples can apply this consistency if there are no conflicts.
2. What's the best way to apply `.framed` to `<body>`? I tried the following, but there was an error even though I have the `elements` preprocessor set up:

   ```css
   /* I have `<body class="framed">` in app.html */
   :global(.framed) {
     min-height: 100vh;
     width: 100%;
     padding: 'spacing-06' 'spacing-05';
     /* padding: 'spacing-06'; it works when I have 1 token instead of 2 */
   }
   ```

   - Workaround: apply the token values directly in the `.framed` class

Related: #1145

**Comment by metonym** [comment, marked as answer]
That's a pretty astute observation. I would recommend manually applying the `.framed` styles to your project.

If the elements preprocessor doesn't work, I would just use `var(--cds-spacing-05)` if using the `all.css` stylesheet.

**Reply by theetrain** [reply]
Thanks for your response, I'm now using `all.css` as you suggested and added the following to my application layout in SvelteKit:

```css
:global(.framed-body) {
  min-height: 100vh;
  width: 100%;
}
@media (min-width: 672px) {
  :global(.framed-body) {
    padding: var(--cds-spacing-06) var(--cds-spacing-05);
  }
}
```

Let me know if I should open issues in other repos to address the preprocessor issue or documentation of UIShell.
