### DISCUSSION TITLE
Can a Datatable be horizontally scrollable?

### DISCUSSION THREAD

**Discussion by cgildenia** [carbon-design-system/carbon-components-svelte#1512] [Q&A] [answered]
Hello all, I have a Datatable with a lot of columns and I haven't been able to get a scrollbar that works just for the table itself.
ATM there is the scrollbar for the web itself, but that doesn't look good enough.

**Comment by theetrain** [comment, marked as answer]
@cgildenia I have this CSS set up for my DataTables: 

```css
  /*
    Table wrapper used to opt into sticky styles

    Usage:
    <div class="table-wrapper">
      <DataTable />
    </div>
  */
  :global(.table-wrapper) {
    overflow-x: scroll;
  }
  /*
    Keep header and toolbar visible on
    wide tables with sticky content
  */
  :global(.table-wrapper .bx--data-table-container) {
    overflow: auto;
  }
  :global(.table-wrapper .bx--data-table-header, .table-wrapper
      .bx--table-toolbar, .table-wrapper .bx--pagination) {
    position: sticky;
    left: 0;
  }
```

And then you can wrap your DataTable with the `table-wrapper` class:

```html
<div class="table-wrapper">
  <DataTable {...tableProps} />
</div>
```

Having a built-in way for tables be scrollable is something I would advocate for.
