### DISCUSSION TITLE
How should breakpoint-specific CSS (or SCSS) be applied (sm/md/lg/xlg/max)?

### DISCUSSION THREAD

**Discussion by wbudd** [carbon-design-system/carbon-components-svelte#1602] [Q&A] [answered]
Toward the bottom of the page at [https://carbondesignsystem.com/guidelines/2x-grid/implementation/](https://carbondesignsystem.com/guidelines/2x-grid/implementation/) there is mention of being able to do something like this:

```scss
.component {
  display: inline;

  /* applies styles inside mixin on md breakpoint or below, like max-width */
  @include carbon--breakpoint-down('md') {
    display: none;
  }
}
```

However, no matter what syntax variation, CSS/SCSS/etc flavor, and npm package I try; SvelteKit complains about the @include part being an "Undefined mixin".

Can you please provide a self-contained example of how to make CSS work along Carbon-defined breakpoints? Preferably including which npm/etc packages are needed besides `carbon-components-svelte` (if any).
