### DISCUSSION TITLE
UIShell disable full width

### DISCUSSION THREAD

**Discussion by boustanihani** [carbon-design-system/carbon-components-svelte#1816] [General]
Hi, is it possible to prevent the UIShell from taking the full width of the page?

**Comment by metonym** [comment]
You can use global CSS to target the header element:

```css
.bx--header {
  max-width: 1200px;
  margin: auto;
}
```

<img width="1408" height="709" alt="Custom UI Shell width" src="https://github.com/user-attachments/assets/e3099643-7252-4482-9f47-8b0469259b96" />
