### ISSUE TITLE
Styling background color of toggle?

### ISSUE THREAD

**Issue by ErraticFox** [carbon-design-system/carbon-components-svelte#1250]
I've tried using

```css
:global(:root) {
	--cds-support-02: red;
}
```
with other combinations of global and root, but no avail. I'd like to NOT customize the color though, and just style that specific instance of the component, but this doesn't work either 
```css
.theme-wrapper > .bx--toggle-input:checked+.bx--toggle-input__label>.bx--toggle__switch::before {
    background-color: red; 
}
```

**Comment by metonym** [comment]
You have the right idea; however, in this instance the CSS specificity must be higher. I added a `span` to the `.bx--toggle__switch` selector.

```css
:global(.bx--toggle-input:checked+.bx--toggle-input__label>span.bx--toggle__switch::before) {
  background-color: blue;
}
```

https://svelte.dev/repl/fa3762a0201043a098744746062aff51?version=3.47.0
