### ISSUE TITLE
how to  hidden TooltipDefinition's bottom line?

### ISSUE THREAD

**Issue by dybxin** [carbon-design-system/carbon-components-svelte#1376]
how to  hidden TooltipDefinition's bottom line?

**Comment by metonym** [comment]
You can override the styles by targeting the class:

```css
:global(.bx--tooltip__trigger.bx--tooltip__trigger--definition) {
  border: 0 !important;
}
```
