### ISSUE TITLE
Toggle has excess margin above, looks wrong in DataTable

### ISSUE THREAD

**Issue by timo** [carbon-design-system/carbon-components-svelte#1413]
First of all, here's a codesandbox: https://codesandbox.io/s/purple-rgb-wc5c2i?file=/App.svelte

and a screenshot:
![image](https://user-images.githubusercontent.com/25167/181000204-0206f51e-b5ad-4546-85c2-2b63e72e3c92.png)

With a simple change in the dev tools, it looks a lot better:

```css
.bx--toggle-input__label .bx--toggle__switch {
  margin-top: 0;
}
```

screenshot of the "fixed" style in my application:

![image](https://user-images.githubusercontent.com/25167/181000773-1848428f-9298-449f-a562-1c41a07c46d2.png)
