### ISSUE TITLE
bx--content applies extraneous left margin

### ISSUE THREAD

**Issue by pheuter** [carbon-design-system/carbon-components-svelte#834]
Not sure if this is intentional but the [example](https://carbon-svelte.vercel.app/framed/UIShell/HeaderNav?theme=white) doesn't appear to have this issue.

```css
.bx--side-nav~.bx--content {
    margin-left: 3rem;
}
```

![image](https://user-images.githubusercontent.com/92698/135629269-09f71f97-d905-4ba4-a1b5-cf2aa2611eae.png)

**Comment by metonym** [comment]
What screen width size is that?

Inspecting the CSS, the following rule kicks in past a certain breakpoint:

```css
@media (max-width: 1056px) {
  .bx--side-nav~.bx--content {
    margin-left: 0;
    padding-left: 1rem;
    padding-right: 1rem;
  }
}
```
