### ISSUE TITLE
Styling Icon in Button

### ISSUE THREAD

**Issue by ranielzed** [carbon-design-system/carbon-components-svelte#942]
How does one go about styling the Icon inside a Button?

I understand you can style an icon by itself but how about when it's used by a component?
I just want to change the color of the Icon.

Thanks

**Comment by metonym** [comment]
I would recommend overriding the icon fill color using global styles.

Try the following:

```css
:global([data-carbon-icon]) {
  fill: red;
}
```
