### ISSUE TITLE
How to replicate toast notification color shade changes?

### ISSUE THREAD

**Issue by ambiguous48** [carbon-design-system/carbon-components-svelte#970]
Is it possible to set a dynamic color on a component with the included themes? I've looked through the docs and searched the issues but couldn't find a solution or an example.

`Toast notification`'s colors change shades as the theme switches from light to dark. How can I replicate those exact colors on some of my other components, icons, etc?

I'm trying to find a way to implement some icons using carbon's existing '`success`' or '`error`' colors.

**Comment by metonym** [comment]
If you are using `all.css`, you can use the tokens defined as CSS variables. There are 400+ tokens used per theme.

Examples:

```css
.component {
  color: var(--cds-inverse-support-01);
  margin-bottom: var(--cds-spacing-08);
}
```
